import "./globals.css"
import type { Metadata } from "next"
// import { Inter } from "next/font/google";
import NavBar from "./NavBar"
import "@radix-ui/themes/styles.css"
import { Container, Theme, ThemePanel } from "@radix-ui/themes"
import AuthProvider from "./auth/Provider"
import QueryClientProvider from "./QueryClientProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import CursorManager from "./CursorManager"
import "@pigment-css/react/styles.css"
import DynamicBezierCurve from "./components/navbar/test"
import { ScrollableProvider } from "./context/ScrollableContext"

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {" "}
        {/* className={inter.className} */}
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance="light" accentColor="sky" radius="small">
              <ScrollableProvider>
                <NavBar />
                <DynamicBezierCurve />
                <CursorManager />
                <main className="pt-16">
                  <Container>{children}</Container>
                </main>
              </ScrollableProvider>
            </Theme>
            <ReactQueryDevtools />
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
