import "./globals.css"
import type { Metadata } from "next"
// import { Inter } from "next/font/google";
import NavBar from "./NavBar"
import "@radix-ui/themes/styles.css"
import { Theme } from "@radix-ui/themes"
import AuthProvider from "./auth/Provider"
import QueryClientProvider from "./QueryClientProvider"
import { ReactQueryDevtools } from "@tanstack/react-query-devtools"
import CursorManager from "./CursorManager"
import "@pigment-css/react/styles.css"
import { ThemeProvider } from "./context/DarkModeContext"
import { xTheme } from "./service/ThemeService"

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script id="my-script" src="/index.js" />
      </head>
      <body style={xTheme.layoutBackground}>
        {/* className={inter.className} */}
        <QueryClientProvider>
          <AuthProvider>
            <ThemeProvider>
              <Theme appearance="light" accentColor="sky" radius="small">
                <NavBar />
                <CursorManager />
                <main className="pt-14">{children}</main>
              </Theme>
              <ReactQueryDevtools />
            </ThemeProvider>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  )
}
